### ISSUE TITLE
请问固件要自己编译么..没找到下载地址

### ISSUE THREAD

**Issue by alicechino** [RikudouPatrickstar/R4S-OpenWrt-Lean#2]
谢谢大佬了

**Comment by RikudouPatrickstar** [comment]
这个项目是可以在线编译自动发布的。目前 lean 那边没做好适配， https://github.com/1715173329/openwrt/tree/1806-k54-nanopi-r4s 这个项目在做 r4s 的适配，但还要再等一等。所以固件过一段时间才会有。

**Comment by alicechino** [comment]
非常感谢！
