### ISSUE TITLE
希望加回挂载，共享，升级

### ISSUE THREAD

**Issue by wifiway520** [RikudouPatrickstar/R4S-OpenWrt-Lean#3]
感谢大佬制作固件，不会编译，而且有共享需求，所以希望大佬添加挂载点，共享以及升级等功能，再次感谢大佬

**Comment by RikudouPatrickstar** [comment]
你可以 fork 一下项目，将 SCRIPTS/my_prepare_package.sh 中 “移除 LuCI 部分页面” 的代码移除。开启 Actions workflows 之后即可触发在线编译（手动点 ⭐ 可以启动编译）。

**Comment by RikudouPatrickstar** [comment]
Samba共享 是包含在固件中的，挂载和升级其实可以通过 SSH 来操作。
你可以 fork 一下项目，将 SCRIPTS/my_prepare_package.sh 中 “移除 LuCI 部分页面” 的代码移除，就能恢复挂载和升级。开启 Actions workflows 之后可触发在线编译（手动点 ⭐ 可以启动编译）。

**Comment by wifiway520** [comment]
谢谢大佬
